import {
  Cpu, Radar, Terminal, ShieldCheck, Zap, BrainCircuit, Sparkles, CheckCircle2,
} from "lucide-react";
import type { QuickPromptCategory } from "./types";

export const QUICK_PROMPT_CATEGORIES: QuickPromptCategory[] = [
  {
    name: "🛡️ Security & Fraud",
    prompts: [
      { label: "Fraud Detection Scan", icon: Radar, prompt: "Run a complete fraud detection scan" },
      { label: "Multi-Account Abuse", icon: Radar, prompt: "Detect multi-account abuse" },
      { label: "Traffic Threat Analysis", icon: ShieldCheck, prompt: "Analyze traffic patterns for threats" },
      { label: "Low Trust Users", icon: Radar, prompt: "Find users with trust score below 50 and explain why" },
      { label: "Suspicious Activities", icon: Radar, prompt: "List all pending suspicious activities" },
      { label: "Ban Audit Log", icon: ShieldCheck, prompt: "Show recent ban/unban actions from the audit log" },
    ],
  },
  {
    name: "💰 Finance & Wallet",
    prompts: [
      { label: "Financial Report (30d)", icon: Zap, prompt: "Show financial report for last 30 days" },
      { label: "Pending Withdrawals", icon: Zap, prompt: "Show all pending withdrawal requests" },
      { label: "Approve All Topups", icon: CheckCircle2, prompt: "Approve all pending topups" },
      { label: "Wallet Summary", icon: Zap, prompt: "Show total platform wallet balance and top 10 richest users" },
    ],
  },
  {
    name: "📋 Content & Moderation",
    prompts: [
      { label: "User Complaints", icon: ShieldCheck, prompt: "Show all pending user reports and complaints with details" },
      { label: "Pending Content Review", icon: Terminal, prompt: "List all pending clip reports and user reports that need review" },
      { label: "Reported Clips", icon: Terminal, prompt: "List all pending clip reports" },
      { label: "Mod Applications", icon: ShieldCheck, prompt: "Show pending moderator applications" },
    ],
  },
  {
    name: "🎮 Tournaments & Events",
    prompts: [
      { label: "Tournament Analytics", icon: BrainCircuit, prompt: "Give me analytics on all tournaments — participation, revenue, completion rates" },
      { label: "Create Tournament", icon: Sparkles, prompt: "Create a Free Fire tournament for tomorrow" },
      { label: "Create Gift Code", icon: Zap, prompt: "Create gift code WELCOME50 worth ₹50" },
      { label: "Smart Recommendations", icon: Sparkles, prompt: "Get smart recommendations for tournaments" },
    ],
  },
  {
    name: "👥 User Management",
    prompts: [
      { label: "Recent Signups", icon: Cpu, prompt: "List recent signups from last 7 days" },
      { label: "Inactive Users", icon: Cpu, prompt: "Find users who haven't logged in for 30+ days" },
      { label: "Mass Notify Users", icon: Sparkles, prompt: "Send a notification to all users about upcoming maintenance" },
    ],
  },
  {
    name: "⚙️ System & Diagnostics",
    prompts: [
      { label: "Platform Health Check", icon: Cpu, prompt: "Give me a full platform health check" },
      { label: "Deep Diagnostics", icon: Terminal, prompt: "Run deep system diagnostics" },
      { label: "Optimization Report", icon: BrainCircuit, prompt: "Generate optimization report" },
      { label: "Open Support Tickets", icon: Terminal, prompt: "List all open support tickets" },
      { label: "Live Streams", icon: Cpu, prompt: "Show all currently live streams" },
      { label: "Cleanup Stale Data", icon: Terminal, prompt: "Run cleanup scan on all stale data (dry run)" },
    ],
  },
  {
    name: "📊 Advanced Analytics",
    prompts: [
      { label: "Revenue Breakdown", icon: Zap, prompt: "Show detailed revenue breakdown for last 30 days with top spenders" },
      { label: "Growth Metrics", icon: BrainCircuit, prompt: "Show growth metrics: DAU/MAU, signup trends, retention" },
      { label: "Compare Last 2 Weeks", icon: Cpu, prompt: "Compare platform metrics: last 7 days vs previous 7 days" },
      { label: "Whale Analysis", icon: Radar, prompt: "Run whale analysis — find top spending users with full details" },
      { label: "Churn Prediction", icon: Radar, prompt: "Run churn prediction — find at-risk users likely to leave" },
      { label: "Tournament ROI", icon: BrainCircuit, prompt: "Analyze tournament ROI — which tournaments are profitable" },
      { label: "Export Users CSV", icon: Terminal, prompt: "Export all users data as CSV" },
      { label: "Top Leaderboard", icon: Sparkles, prompt: "Show leaderboard: top earners, most wins, highest trust scores" },
    ],
  },
];

export const TOOL_LABELS: Record<string, string> = {
  ban_user: "Ban User", unban_user: "Unban User", get_user_details: "Get User Details",
  delete_user_data: "Delete User", set_user_role: "Set User Role", mass_ban_users: "Mass Ban",
  list_users: "List Users", suspend_user: "Suspend User", verify_user: "Verify User",
  approve_withdrawal: "Approve Withdrawal", reject_withdrawal: "Reject Withdrawal",
  approve_topup: "Approve Topup", reject_topup: "Reject Topup",
  bulk_approve_topups: "Bulk Approve Topups", bulk_approve_withdrawals: "Bulk Approve Withdrawals",
  credit_user_wallet: "Credit Wallet", debit_user_wallet: "Debit Wallet", refund_user: "Refund User",
  list_pending_withdrawals: "List Withdrawals", list_pending_topups: "List Topups",
  get_recent_transactions: "Recent Transactions", get_financial_report: "Financial Report",
  create_tournament: "Create Tournament", update_tournament: "Update Tournament",
  delete_tournament: "Delete Tournament", list_tournaments: "List Tournaments",
  declare_tournament_winner: "Declare Winner", get_tournament_participants: "Get Participants",
  get_tournament_analytics: "Tournament Analytics", create_gift_code: "Create Gift Code",
  toggle_gift_code: "Toggle Gift Code", list_gift_codes: "List Gift Codes",
  resolve_ticket: "Resolve Ticket", list_open_tickets: "List Tickets",
  create_announcement: "Create Announcement", delete_announcement: "Delete Announcement",
  list_announcements: "List Announcements", send_notification: "Send Notification",
  broadcast_maintenance: "Broadcast Maintenance", detect_fraud: "Fraud Scan",
  flag_suspicious_user: "Flag User", get_login_activity: "Login Activity",
  detect_multi_accounts: "Multi-Account Detect", list_recent_signups: "Recent Signups",
  list_user_reports: "List Reports", review_user_report: "Review Report",
  list_ban_audit_log: "Audit Log", get_platform_stats: "Platform Stats",
  get_platform_health: "Health Check", analyze_user_behavior: "User Analytics",
  get_user_risk_score: "Risk Score", update_site_setting: "Update Setting",
  get_traffic_analysis: "Traffic Analysis", get_system_health_deep: "Deep Health Check",
  get_activity_log: "Activity Log", get_platform_diagnostics: "Diagnostics",
  send_admin_alert: "Admin Alert", get_optimization_report: "Optimization Report",
  get_smart_recommendations: "Smart Recommendations",
  delete_clip: "Delete Clip", list_clip_reports: "Clip Reports", review_clip_report: "Review Clip Report",
  update_user_profile: "Update Profile", shadow_ban_user: "Shadow Ban", verify_user_badge: "Verify Badge",
  reset_user_password: "Reset Password", recalculate_trust_score: "Trust Score",
  list_mod_applications: "Mod Applications", review_mod_application: "Review Mod App",
  mass_credit_users: "Mass Credit", mass_notify_users: "Mass Notify",
  refund_all_tournament_participants: "Refund Tournament",
  list_suspicious_activities: "Suspicious Activities", review_suspicious_activity: "Review Activity",
  get_user_conversations: "User DMs", delete_messages: "Delete Messages",
  list_live_streams: "Live Streams", end_live_stream: "End Stream",
  list_apk_releases: "APK Releases", create_apk_release: "Create APK Release",
  list_automation_rules: "Automation Rules", create_automation_rule: "Create Rule",
  toggle_automation_rule: "Toggle Rule",
  // New advanced tools
  export_data_csv: "Export CSV", cross_table_analytics: "Cross Analytics",
  compare_periods: "Compare Periods", find_users_by_criteria: "Find Users",
  bulk_action: "Bulk Action", get_user_timeline: "User Timeline",
  get_revenue_breakdown: "Revenue Breakdown", get_growth_metrics: "Growth Metrics",
  cleanup_stale_data: "Cleanup Data", get_leaderboard_data: "Leaderboard",
};
